# Generated by Django 3.1.6 on 2022-03-30 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='textType',
            field=models.CharField(blank=True, choices=[('text/plain', 'Plaintext'), ('text/markdown', 'Markdown')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='like',
            name='type',
            field=models.CharField(default='like', max_length=200),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
