# Generated by Django 3.1.6 on 2022-03-29 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='type',
            field=models.CharField(default='like', max_length=200),
        ),
    ]
