# Generated by Django 3.2.10 on 2022-03-31 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='summary',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='like',
            name='object',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='like',
            name='type',
            field=models.CharField(default='like', max_length=200),
        ),
    ]
