# Generated by Django 3.1.6 on 2022-03-30 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20220328_2308'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='shared',
            field=models.BooleanField(default=False),
        ),
    ]
