# Generated by Django 3.1.6 on 2022-03-30 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='followers',
            options={'verbose_name': 'Follower', 'verbose_name_plural': 'Followers'},
        ),
    ]
