# Generated by Django 3.1.6 on 2022-03-28 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConnectionNode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('auth_username', models.CharField(max_length=255)),
                ('auth_password', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'connection node',
                'verbose_name_plural': 'connection nodes',
            },
        ),
    ]
