# Generated by Django 3.1.6 on 2022-03-28 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    def create_connection_nodes(apps, schema_editor):
        """
        Create some connection nodes
        """
        ConnectionNode = apps.get_model('common', 'ConnectionNode')
        ConnectionNode.objects.create(
            name='T7Self',
            url='https://c404-social-distribution.herokuapp.com/service/',
            auth_username='admin',
            auth_password='admin')
        ConnectionNode.objects.create(
            name='T2Lefan',
            url='https://social-dist-wed.herokuapp.com/service/',
            auth_username='team02admin',
            auth_password='admin')
        ConnectionNode.objects.create(
            name='T5Kerry',
            url='https://cmput404-w22-project-backend.herokuapp.com/service/server_api/',
            auth_username='proxy',
            auth_password='proxy123!')
        ConnectionNode.objects.create(
            name='T7SelfClone',
            url="https://cmput4042ndnetwork.herokuapp.com/service/",
            auth_username='admin',
            auth_password='admin')
        # remain this order! put them at the back
        ConnectionNode.objects.create(
            name='T8Ruilin',
            url="https://project-socialdistribution.herokuapp.com/api/",
            auth_username='team7',
            auth_password='t8H3f@F2')

    operations = [
        migrations.CreateModel(
            name='ConnectionNode',
            fields=[
                ('id',
                 models.AutoField(auto_created=True,
                                  primary_key=True,
                                  serialize=False,
                                  verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('auth_username', models.CharField(max_length=255)),
                ('auth_password', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'connection node',
                'verbose_name_plural': 'connection nodes',
            },
        ),
        migrations.RunPython(create_connection_nodes),
    ]