# Generated by Django 3.1.6 on 2022-02-24 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20220224_0335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profileImg',
            field=models.ImageField(blank=True, default='profile_images/avatar1.png', upload_to='profile_images'),
        ),
    ]
