# Generated by Django 3.1.6 on 2022-02-24 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20220224_0412'),
    ]

    operations = [
        migrations.CreateModel(
            name='FollowerCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follower', models.CharField(max_length=100)),
                ('user', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='author',
            name='profileImage',
            field=models.ImageField(blank=True, default='profile_images/avatar1.png', upload_to='profile_images'),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
