# Generated by Django 3.1.6 on 2022-03-27 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_followers'),
    ]

    def create_connection_nodes(apps, schema_editor):
        """
        Create some connection nodes
        """
        ConnectionNode = apps.get_model('myapp', 'ConnectionNode')
        ConnectionNode.objects.create(
            name='Team 2 - Lefan',
            url='https://social-dist-wed.herokuapp.com/service/',
            auth_username='team02admin',
            auth_password='admin')
        ConnectionNode.objects.create(
            name='Team 5 - Kerry',
            url='https://cmput404-w22-project-backend.herokuapp.com/service/',
            auth_username='proxy',
            auth_password='proxy123!')
        ConnectionNode.objects.create(
            name='Self Connection - Team 7',
            url="https://cmput4042ndnetwork.herokuapp.com/service/",
            auth_username='admin',
            auth_password='admin')

    operations = [
        migrations.CreateModel(
            name='ConnectionNode',
            fields=[
                ('id',
                 models.AutoField(auto_created=True,
                                  primary_key=True,
                                  serialize=False,
                                  verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('auth_username', models.CharField(max_length=255)),
                ('auth_password', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'connection node',
                'verbose_name_plural': 'connection nodes',
            },
        ),
        migrations.RunPython(create_connection_nodes),
    ]
