# Generated by Django 4.0.2 on 2022-02-25 03:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20220224_0524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendfollowrequest',
            name='actor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_request_sender', to='myapp.author'),
        ),
        migrations.AlterField(
            model_name='friendfollowrequest',
            name='object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_request_receiver', to='myapp.author'),
        ),
    ]
