# Generated by Django 3.1.6 on 2022-02-25 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_friendfollowrequest_actor_and_more'),
        ('myapp', '0002_auto_20220225_0344'),
    ]

    operations = [
    ]
