# Generated by Django 3.1.6 on 2022-03-02 23:05

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_auto_20220301_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='profileImage',
            field=models.ImageField(blank=True, default='profile_images/avatar1.png', upload_to='profile_images'),
        ),
        migrations.AddField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(default=111, on_delete=django.db.models.deletion.CASCADE, to='myapp.author'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
