# Generated by Django 3.1.6 on 2022-03-28 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('posts', '0001_initial'),
        ('authors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inbox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='inbox', max_length=200)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authors.author')),
                ('items', models.ManyToManyField(to='posts.Post')),
            ],
        ),
        migrations.CreateModel(
            name='InboxItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inbox_item_type', models.CharField(choices=[('like', 'like'), ('post', 'post'), ('comment', 'comment'), ('friendfollowrequest', 'friendfollowrequest')], max_length=20)),
                ('is_read', models.BooleanField(default=False)),
                ('item_id', models.CharField(max_length=255)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('inbox', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inboxes.inbox')),
            ],
        ),
    ]
