# Generated by Django 3.2.10 on 2022-03-31 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inboxes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inboxitem',
            old_name='item_id',
            new_name='object_id',
        ),
    ]
